# Generated by Django 2.1.1 on 2018-09-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=50)),
                ('area_leader', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=50)),
                ('members', models.CharField(max_length=50)),
                ('work_number', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('set_time', models.CharField(max_length=50)),
            ],
        ),
    ]
